### ISSUE TITLE
TCP id

### ISSUE THREAD

**Issue by bShnaider** [tuxnsk/nodejs_libmodbus#12]
hi, 
How can I connect to specific slave with specific id?
In the RTU connection I specify the slave Id when creating connection while in the TCP connection there is no option.

I would appreciate your help,
thanks.

**Comment by robinxc** [comment]
I want used TCP  slaveid ,but  this connect to specific slave with specific id

**Comment by bShnaider** [comment]
I was able to do it with this project:
https://github.com/morkai/h5.modbus

**Comment by robinxc** [comment]
Thinks !

**Comment by ProteusCortex** [comment]
You could also use native functions. Check this example from README:

```javascript
var log = console.log;
var native = require('modbus').native;

// create context
var ctx = native.new_tcp("127.0.0.1", 1502);

/* Here you can set the slave id */
native.set_slave(ctx, 255);

// connect to slave device
native.connect(ctx);

// get value
var result = [];
native.read_registers(ctx, 2, 1, result);
log(result[0]);

// set value
native.write_bit(ctx, 1, native.OFF);

// close context
native.close(ctx);
native.free(ctx);
```
