### ISSUE TITLE
Float number in holding register

### ISSUE THREAD

**Issue by tomasinouk** [tuxnsk/nodejs_libmodbus#13]
Hi, is it possible to have float number e.g.. 3.197495 in holding register? When I initiate data data.setReg(1, 3.197495);
data.dumpData();
it shows as a valid register value. After the server is created and assigned the data object it is converted to integer.
Could this behaviour be changed? thanks

**Comment by jkeiter** [comment]
I have used the following for float in main.cpp:
// int modbus_read_registers(modbus_t *ctx, int addr, int nb, uint16_t *dest);
// return float from 4 bytes in Modbus format (ABCD)
Handle<Value> js_read_float_register(const Arguments& args) {
	modbus_t *ctx = static_cast<modbus_t *>(External::Unwrap(args[0]));
	int addr = Local<Integer>::Cast(args[1])->Int32Value();
	int nb = Local<Integer>::Cast(args[2])->Int32Value();
	Local<Array> dest_arr = Local<Array>::Cast(args[3]);

	float f;
    nb = nb * 2;
	uint16_t dest[nb];
	int ret = modbus_read_registers(ctx, addr, nb, dest);
	uint32_t i;
    i = (((uint32_t)dest[1]) << 16) + dest[0];
	memcpy(&f, &i, sizeof(float));
    dest_arr->Set(0, Number::New(f));

	return Integer::New(ret);
}

// int modbus_read_registers(modbus_t *ctx, int addr, int nb, uint16_t *dest);
// return multiple floats from 4 bytes in Modbus format (ABCD)
Handle<Value> js_read_float_registers(const Arguments& args) {
	modbus_t *ctx = static_cast<modbus_t *>(External::Unwrap(args[0]));
	int addr = Local<Integer>::Cast(args[1])->Int32Value();
	int nb = Local<Integer>::Cast(args[2])->Int32Value();
	Local<Array> dest_arr = Local<Array>::Cast(args[3]);

	float f;
    int len = nb * 2;
	uint16_t dest[len];
	uint32_t buf;
	int ret = modbus_read_registers(ctx, addr, len, dest);
	for (int i = 0; i < nb; i++) {
		buf = (((uint32_t)dest[(i*2)+1]) << 16) + dest[i*2];
		memcpy(&f, &buf, sizeof(float));
	    dest_arr->Set(i, Number::New(f)); // TODO
	}
	return Integer::New(ret);
}
// int modbus_read_registers(modbus_t *ctx, int addr, int nb, uint16_t *dest);
// return float from 4 bytes in inversed Modbus format (DCBA))
Handle<Value> js_read_float_register_dcba(const Arguments& args) {
	modbus_t *ctx = static_cast<modbus_t *>(External::Unwrap(args[0]));
	int addr = Local<Integer>::Cast(args[1])->Int32Value();
	int nb = Local<Integer>::Cast(args[2])->Int32Value();
	Local<Array> dest_arr = Local<Array>::Cast(args[3]);

	float f;
    nb = nb * 2;
	uint16_t dest[nb];
	int ret = modbus_read_registers(ctx, addr, nb, dest);
	uint32_t i;
	i = bswap_32((((uint32_t)dest[1]) << 16) + dest[0]);
	memcpy(&f, &i, sizeof(float));
    dest_arr->Set(0, Number::New(f));

    return Integer::New(ret);
}

// int modbus_read_registers(modbus_t *ctx, int addr, int nb, uint16_t *dest);
// return multiple floats from 4 bytes in inversed Modbus format (DCBA))
Handle<Value> js_read_float_registers_dcba(const Arguments& args) {
	modbus_t *ctx = static_cast<modbus_t *>(External::Unwrap(args[0]));
	int addr = Local<Integer>::Cast(args[1])->Int32Value();
	int nb = Local<Integer>::Cast(args[2])->Int32Value();
	Local<Array> dest_arr = Local<Array>::Cast(args[3]);

	float f;
	int len = nb * 2;
	uint16_t dest[len];
	uint32_t buf;
	int ret = modbus_read_registers(ctx, addr, len, dest);
	for (int i = 0; i < nb; i++) {
		    buf = bswap_32((((uint32_t)dest[(i*2)+1]) << 16) + dest[i*2]);
			memcpy(&f, &buf, sizeof(float));
		    dest_arr->Set(i, Number::New(f)); // TODO
		}

	return Integer::New(ret);
}

// in modbus.js I have //

// params: adr, count
	funcs['getFloat'] = function () {
		if (isLocal) {
			var end = adr + count;
			
			if (adr < 0 || adr >= jso.nb_registers || end > jso.nb_registers) {
				a.err(func + ': invalid address');
				return null;
			}
			
			var ret = [], j = 0;
			for (var i = adr; i < end; i++) {
				ret[j] = jso.tab_registers[i];
				j++;
			}
			
			return ret;
		} else {
			var val = [];
		
			if (mb.read_float_register(ctx, adr, count, val) == -1) {
				a.err(func + ': ' + mb.strerror());
				return null;
			}
			
			return Number(val);
		}
	};

I have tested single float set and return with the PLC I am using; reading multiple regs in js is incomplete and needs work --
