### ISSUE TITLE
RTU Id Missing

### ISSUE THREAD

**Issue by sperrydd** [tuxnsk/nodejs_libmodbus#2]
I was getting Connection Timed Out Error using RTU mode.
Found in your modbus.js file about line 694 you were not returning device ID.

Should be like:

return {
		type: 'RTU',
		id: id,
		device: device,
		baud: baud,
		parity: parity,
		dataBit: dataBit,
		stopBit: stopBit
	};

Thanks for creating module...

**Comment by ProteusCortex** [comment]
Fixed.
