### ISSUE TITLE
install modbus not working

### ISSUE THREAD

**Issue by brabant-v** [tuxnsk/nodejs_libmodbus#25]
I can't seem to get modbus installed 
tried various things from the most obvious google searches but none seem to help.
![modbus install](https://cloud.githubusercontent.com/assets/17061988/12819758/9fd0caba-cb5c-11e5-801b-2fcf922132e1.png)

**Comment by num-lock** [comment]
Taken from the `README.md`:

> Now working only in *nix system.

Windows is out of the scope. (Which is what you are apparently using)

**Comment by brabant-v** [comment]
I was doubting if this was the issue but wasn't shure.  Thanks for the confirmation

**Comment by num-lock** [comment]
To be honest, your actual problem appears to be that you are most likely missing the build tools required for node-gyp to work. But even if you had them you'd be out of luck.

**Comment by brabant-v** [comment]
I've installed a linux machine last night but still encountering the same errors.
there's a problem with the npm installer.

**Comment by brabant-v** [comment]
![screenshot from 2016-02-05 10_09_05](https://cloud.githubusercontent.com/assets/17061988/12842085/b9cc3762-cbf0-11e5-8938-8d18c6c6558a.png)

didn't read it the eroors carefully enough "this is most likely a problem with the modbus package"

**Comment by num-lock** [comment]
That's the standard message when the install script is failing, which is trying to call node-gyp at some point. If your would really read your error messages carefully, you'll notice that you are even missing the `git` command.

**Comment by brabant-v** [comment]
I've only been using this since monday hence the beginners mistakes.
You have any idea what i can do to make this work (starting with installing git)

**Comment by num-lock** [comment]
You need `git` and everything necessary for [node-gyp](https://github.com/nodejs/node-gyp) obviously. This package is just a wrapper for another library (libmodbus) after all.

**Comment by tuxnsk** [comment]
install git previously

2016-02-05 15:13 GMT+06:00 brabant-v <notifications@github.com>:

> [image: screenshot from 2016-02-05 10_09_05]
> <https://cloud.githubusercontent.com/assets/17061988/12842085/b9cc3762-cbf0-11e5-8938-8d18c6c6558a.png>
>
> didn't read it the eroors carefully enough "this is most likely a problem
> with the modbus package"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuxnsk/nodejs_libmodbus/issues/25#issuecomment-180262221>
> .
>



-- 
Contacts: http://tuxnsk.ru/
