### ISSUE TITLE
HandleScope Error

### ISSUE THREAD

**Issue by digitizer0** [tuxnsk/nodejs_libmodbus#26]
When running "master.js" example I get
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope

If I'm running "master_native.js" example everything seems ok.
However I would prefer a non-blocking solution.

Using Nodejs 5.6.0 and Modbus 0.0.14

**Comment by jkeiter** [comment]
I added HandleScope scope(isolate); below every instance of Isolate* isolate = v8::Isolate::GetCurrent();
to make it work..

**Comment by Disminder** [comment]
Yes, previous answer helped me too (Mac OS 10.11.4, Ubuntu 16.04)
