### ISSUE TITLE
install err  

### ISSUE THREAD

**Issue by robinxc** [tuxnsk/nodejs_libmodbus#29]
nodejs_libmodbus]# node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@4.3.1 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/usr/local/WindIOT/node_modules/nodejs_libmodbus/build'
  CXX(target) Release/obj.target/modbus_binding/src/main.o
In file included from ../src/main.cpp:2:
/root/.node-gyp/4.3.1/include/node/v8.h:336: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/4.3.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/root/.node-gyp/4.3.1/include/node/v8.h:353: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/root/.node-gyp/4.3.1/include/node/v8.h:360: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/root/.node-gyp/4.3.1/include/node/v8.h:364: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/root/.node-gyp/4.3.1/include/node/v8.h:430: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: At global scope:
/root/.node-gyp/4.3.1/include/node/v8.h:469: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/4.3.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/root/.node-gyp/4.3.1/include/node/v8.h:790: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/root/.node-gyp/4.3.1/include/node/v8.h:815: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/root/.node-gyp/4.3.1/include/node/v8.h:827: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: At global scope:
/root/.node-gyp/4.3.1/include/node/v8.h:852: 错误：expected unqualified-id before ‘using’
/root/.node-gyp/4.3.1/include/node/v8.h:1089: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h:1095: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/root/.node-gyp/4.3.1/include/node/v8.h:3205: 错误：‘nullptr’在此作用域中尚未声明
/root/.node-gyp/4.3.1/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/root/.node-gyp/4.3.1/include/node/v8.h:7164: 错误：‘nullptr’在此作用域中尚未声明
../src/main.cpp: In function ‘void tcp_accept_a(uv_work_t*, int)’:
../src/main.cpp:750: 错误：‘Handle’在此作用域中尚未声明
../src/main.cpp:750: 错误：expected primary-expression before ‘>’ token
../src/main.cpp:750: 错误：‘argv’在此作用域中尚未声明
../src/main.cpp: In function ‘void receive_a(uv_work_t*, int)’:
../src/main.cpp:809: 错误：‘Handle’在此作用域中尚未声明
../src/main.cpp:809: 错误：expected primary-expression before ‘>’ token
../src/main.cpp:809: 错误：‘argv’在此作用域中尚未声明
../src/main.cpp: In function ‘void connect_a(uv_work_t*, int)’:
../src/main.cpp:862: 错误：‘Handle’在此作用域中尚未声明
../src/main.cpp:862: 错误：expected primary-expression before ‘>’ token
../src/main.cpp:862: 错误：‘argv’在此作用域中尚未声明
../src/main.cpp: At global scope:
../src/main.cpp:933: 错误：变量或字段‘init’声明为 void
../src/main.cpp:933: 错误：‘Handle’在此作用域中尚未声明
../src/main.cpp:933: 错误：expected primary-expression before ‘>’ token
../src/main.cpp:933: 错误：‘target’在此作用域中尚未声明
../src/main.cpp:1068: 错误：变量或字段‘Initialize’声明为 void
../src/main.cpp:1068: 错误：‘Handle’在此作用域中尚未声明
../src/main.cpp:1068: 错误：expected primary-expression before ‘>’ token
../src/main.cpp:1068: 错误：‘exports’在此作用域中尚未声明
../src/main.cpp:1069: 错误：‘init’在此作用域中尚未声明
../src/main.cpp:1069: 错误：‘node::node_module’的初始值设定项太多
make: *** [Release/obj.target/modbus_binding/src/main.o] 错误 1
make: Leaving directory `/usr/local/WindIOT/node_modules/nodejs_libmodbus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/node/v4.3.1/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/usr/local/node/v4.3.1/bin/node" "/usr/local/node/v4.3.1/bin/node-gyp" "build"
gyp ERR! cwd /usr/local/WindIOT/node_modules/nodejs_libmodbus
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by Disminder** [comment]
Which OS do you have? And from where you trying to install (npm repo or git repo)?
