### ISSUE TITLE
Random data when reading with native connection

### ISSUE THREAD

**Issue by acrive82** [tuxnsk/nodejs_libmodbus#30]
Hi 

I'm trying to connect to modbus with native connection. Many times the data returned is totally randomize. 

If I try write a value and after to read it, have a random value.

**Comment by Disminder** [comment]
Modbus TCP, yes?

It's probably error in libmodbus. I'm gonna to rewrite bindings to latest libmodbus version soon, just don't have enough time now.

**Comment by acrive82** [comment]
Yes! With TCP.

**Comment by Disminder** [comment]
Rewrite to latest libmodbus version didn't help =_=
Gonna make some experiments - I just didn't understand, why M libmodbus - S libmodbus works and M libmodbus - S real device - not.

**Comment by Disminder** [comment]
Not libmodbus error - you need to use `native.set_slave(ctx, id)` function to set which ID you requesting on the slave device. It helped me. Probably I'll add 0 as a default ID.
