### ISSUE TITLE
ошибка при запуске

### ISSUE THREAD

**Issue by reejinbouk** [tuxnsk/nodejs_libmodbus#32]
Добрый день.
почему то при запуске получаю ошибку постоянно:
node old.js
`FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope`

запускаю такой файл:
`var log = console.log;`
`var mb = require('modbus').create();`

`mb.onError(function (msg) {`
`  log('ERROR', msg);`
`});`

`var ctx = mb.createMaster({`

  `con: mb.createConRtu(207, '/dev/ttyUSB3', 9600),`

  `onConnect: function () {`
 `   log('onConnect');`
 `   log(ctx.getReg(2));`
  `  ctx.setBit(1, false);`
  `  ctx.destroy();`
 ` },`
`  onDestroy: function () {`
`    log('onDestroy');`
`  }`
`});`

**Comment by Disminder** [comment]
Добрый. Версия из npm или с репозитория? Подозреваю что с npm, там старая. Устанавливайте с помощью `npm install https://github.com/tuxnsk/nodejs_libmodbus/`
