### ISSUE TITLE
Does not work on a Mac OS X 10.9 64 bit

### ISSUE THREAD

**Issue by chaser92** [tuxnsk/nodejs_libmodbus#4]
Was unable to fix this problem. The library has linking problems with .dyld shared libraries (OS X .so equivalent). It builds yet crashes when any modbus function is called.

**Comment by nzfarmer1** [comment]
Any progress on this one? Have just come unstuck too! thanks

**Comment by nzfarmer1** [comment]
Ok this is as far as I got - using a clone of https://github.com/tuxnsk/nodejs_libmodbus:

1. First remove the dependency on linux in binding.gyp

{
	'targets': [
		{
			'target_name': 'modbus_binding',
			'cflags': [
				'-Wall',
			],
			'ldflags': [
				'../libmodbus/src/.libs/modbus.o',
				'../libmodbus/src/.libs/modbus-data.o',
				'../libmodbus/src/.libs/modbus-rtu.o',
				'../libmodbus/src/.libs/modbus-tcp.o',
			],
			'include_dirs': [
				'./libmodbus/src/',
			],
			'sources': [
				'./src/main.cpi'
			]
		}
	]
}

2. Secondly replace python2 with python (I use 2.7 anyway) in package.json

I get a clean configure and compile and a resulting ./build/Release/modbus_binding.node

(using npm link within the nodes_libmodbus folder)


However, am stuck here when I try to run node modbus,js

node modbus.js 

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Symbol modbus_binding_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/andrew/dev/node_modules/nodejs_libmodbus/modbus.js:3:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by ProteusCortex** [comment]
I am running OS X 10.9 and I cannot build it using your `binding.gyp`. However, with Node v0.10.37 and the following `binding.gyp` it seems to be working just fine. I will propose to remove the `'OS=="linux"'` condition altogether.
```javascript
{
    'targets': [{
        'target_name': 'modbus_binding',
        'cflags': [
            '-Wall'
        ],
        'ldflags': [
            '../libmodbus/src/.libs/modbus.o',
            '../libmodbus/src/.libs/modbus-data.o',
            '../libmodbus/src/.libs/modbus-rtu.o',
            '../libmodbus/src/.libs/modbus-tcp.o'
        ],
        'include_dirs': [
            './libmodbus/src/'
        ],
        'sources': [
            './src/main.cpp'
        ]
    }]
}
```

**Comment by nzfarmer1** [comment]
Perfect!

**Comment by nzfarmer1** [comment]
John

At least we are getting a clean compile, but:

When I compile with this and run either master.js or master_native I get

mac02-4:examples andrew$ node master.js 
dyld: lazy symbol binding failed: Symbol not found: _modbus_new_tcp
  Referenced from: /Users/andrew/dev/node_modules/nodejs_libmodbus/build/Release/modbus_binding.node
  Expected in: dynamic lookup


When using my osx specific gyp file I get

mac02-4:examples andrew$ node master.js 
ERROR createMasterTcp: Undefined error: 0


mac02-4:examples andrew$ node master_native.js 
61696

**Comment by ProteusCortex** [comment]
I'll look into it.

**Comment by bhadrip** [comment]
+1 I am having the same issue.

**Comment by Disminder** [comment]
It helps to me:

`brew install libmodbus`
and edit binding.gyp like this:
```
{
    'targets': [
        {
            'target_name': 'modbus_binding',
            'cflags': [
                '-Wall',
            ],
        'xcode_settings': {
            'OTHER_CFLAGS': [ '-ObjC' ],
            'OTHER_CPLUSPLUSFLAGS' : ['-std=c++11','-stdlib=libc++', '-v'],
            'OTHER_LDFLAGS': ['-stdlib=libc++'],
            'MACOSX_DEPLOYMENT_TARGET': '10.9',
            'GCC_ENABLE_CPP_EXCEPTIONS': 'YES', 
            },
        'libraries': [
            '../libmodbus/src/.libs/libmodbus.dylib',
        ],
            'include_dirs': [
                './libmodbus/src/',
            ],
            'sources': [
                './src/main.cpp'
            ],
        },
    ]
}
```
Then `./make_libmodbus.sh && node-gyp configure --python=python && node-gyp build`
in `node_modules/modbus`
Mac OS 10.11.4, Node 6.0.0.
Now have 
```
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
```

**Comment by Disminder** [comment]
Fixed by https://github.com/tuxnsk/nodejs_libmodbus/commit/e49bc3e49ec914afa7450fa4b775f47fa7d0d30c
